/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.es.cb.sdro.view;

import br.gov.es.cb.sdro.model.Unidade;
import br.gov.es.cb.sdro.util.UnidadesDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Heitor
 */
public class Unidades extends javax.swing.JInternalFrame {

    List<Unidade> lista = new UnidadesDAO().buscaUnidades();

    /**
     * Creates new form Unidades
     */
    public Unidades() {
        initComponents();
        this.setVisible(true);

        DefaultTableModel modeloTable = (DefaultTableModel) tbl_unidades.getModel();
        while (modeloTable.getRowCount() > 0) {
            modeloTable.removeRow(0);
        }

        for (Unidade unidadeaux : lista) {
            //adiciona unidades na tabela
            modeloTable.addRow(new Object[]{unidadeaux.getIdunidade(), unidadeaux.getNome(), unidadeaux.getIdcomandante(), unidadeaux.getIdsubcomandante()});
            //Imprime textual
            //System.out.println(unidadeaux.getIdunidade() + " - " + unidadeaux.getNome() + " - " + unidadeaux.getIdcomandante());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas_unidade = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_unidades = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbl_cadastro_unidade = new javax.swing.JLabel();
        lbl_nome_unidade = new javax.swing.JLabel();
        txt_nome_unidade = new javax.swing.JTextField();
        lbl_cmt = new javax.swing.JLabel();
        cmb_postograd_cmt = new javax.swing.JComboBox();
        lbl_postoGrad_cmt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_postograd_cmt = new javax.swing.JList();
        lbl_subcmt = new javax.swing.JLabel();
        lbl_postoGrad_subcmt = new javax.swing.JLabel();
        cmb_postograd_subcmt = new javax.swing.JComboBox();
        lbl_militar_cmt = new javax.swing.JLabel();
        lbl_militar_subcmt = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_postograd_subcmt = new javax.swing.JList();
        btn_salvar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Lista de Unidades");

        tbl_unidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nome", "idComandante", "idSubcomandante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_unidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_unidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_unidades);
        if (tbl_unidades.getColumnModel().getColumnCount() > 0) {
            tbl_unidades.getColumnModel().getColumn(0).setResizable(false);
            tbl_unidades.getColumnModel().getColumn(0).setPreferredWidth(15);
            tbl_unidades.getColumnModel().getColumn(1).setResizable(false);
            tbl_unidades.getColumnModel().getColumn(2).setResizable(false);
            tbl_unidades.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        abas_unidade.addTab("Buscar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cadastro_unidade.setText("Cadastro de Unidades");
        jPanel2.add(lbl_cadastro_unidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        lbl_nome_unidade.setText("Nome");
        jPanel2.add(lbl_nome_unidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txt_nome_unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_unidadeActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nome_unidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 170, -1));

        lbl_cmt.setText("Comandante");
        jPanel2.add(lbl_cmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cmb_postograd_cmt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmb_postograd_cmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 100, -1));

        lbl_postoGrad_cmt.setText("Posto/Graduação");
        jPanel2.add(lbl_postoGrad_cmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        list_postograd_cmt.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_postograd_cmt);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 180, 60));

        lbl_subcmt.setText("SubComandante");
        jPanel2.add(lbl_subcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lbl_postoGrad_subcmt.setText("Posto/Graduação");
        jPanel2.add(lbl_postoGrad_subcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        cmb_postograd_subcmt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmb_postograd_subcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 100, -1));

        lbl_militar_cmt.setText("Militar");
        jPanel2.add(lbl_militar_cmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        lbl_militar_subcmt.setText("Militar");
        jPanel2.add(lbl_militar_subcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        list_postograd_subcmt.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(list_postograd_subcmt);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 180, 60));

        btn_salvar.setText("Salvar");
        jPanel2.add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        abas_unidade.addTab("Cadastrar/Alterar", jPanel2);

        getContentPane().add(abas_unidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nome_unidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_unidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_unidadeActionPerformed

    private void tbl_unidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_unidadesMouseClicked
        //captura a linha selecionada para a tela de cadastro
        System.out.println(tbl_unidades.getSelectedRow() + 1);
        abas_unidade.setSelectedIndex(1);

        txt_nome_unidade.setText(lista.get(tbl_unidades.getSelectedRow()).getNome());
    }//GEN-LAST:event_tbl_unidadesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas_unidade;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox cmb_postograd_cmt;
    private javax.swing.JComboBox cmb_postograd_subcmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_cadastro_unidade;
    private javax.swing.JLabel lbl_cmt;
    private javax.swing.JLabel lbl_militar_cmt;
    private javax.swing.JLabel lbl_militar_subcmt;
    private javax.swing.JLabel lbl_nome_unidade;
    private javax.swing.JLabel lbl_postoGrad_cmt;
    private javax.swing.JLabel lbl_postoGrad_subcmt;
    private javax.swing.JLabel lbl_subcmt;
    private javax.swing.JList list_postograd_cmt;
    private javax.swing.JList list_postograd_subcmt;
    private javax.swing.JTable tbl_unidades;
    private javax.swing.JTextField txt_nome_unidade;
    // End of variables declaration//GEN-END:variables

}
